# Generated by Django 4.1.7 on 2023-03-21 08:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=True),
        ),
    ]
