# Generated by Django 4.1.7 on 2023-03-22 07:29

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_news_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='News.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='caption',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='News/categories'),
        ),
    ]
