# Generated by Django 4.1.7 on 2023-03-22 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_remove_news_category_alter_category_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='News.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='News.category'),
        ),
    ]
