# Generated by Django 4.1.7 on 2023-03-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_alter_news_subcategory_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '1. Category'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': '2.Category'},
        ),
    ]
