# Generated by Django 4.1.7 on 2023-03-22 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_alter_newspost_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 22, 19, 8, 1, 978580)),
        ),
    ]
