# Generated by Django 4.1.7 on 2023-03-24 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_newspost_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'verbose_name': '2. NewsPost'},
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='newspost',
            name='caption',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='newspost',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='News.category'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 24, 21, 59, 32, 748780)),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
