# Generated by Django 4.1.7 on 2023-03-24 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0014_alter_newspost_date_alter_newspost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 24, 22, 32, 59, 578821)),
        ),
    ]
